"""add poll models

Revision ID: 348283e0d66f
Revises: 
Create Date: 2026-05-22 16:35:04.138088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348283e0d66f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_option_post_id'), ['post_id'], unique=False)

    op.create_table('poll_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_option.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_single_vote_per_poll')
    )
    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_vote_post_id'), ['post_id'], unique=False)

    # ================= 🚀 核心修正區塊 =================
    # 1. 先創建允許為空的欄位
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_type', sa.String(length=20), nullable=True))

    # 2. 將所有現存的舊貼文強制更新為 'text' 類型
    op.execute("UPDATE post SET post_type = 'text' WHERE post_type IS NULL")

    # 3. 將該欄位改為實體資料庫約束的 NOT NULL
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('post_type', nullable=False)
    # ==================================================

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_type')

    with op.batch_alter_table('poll_vote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_vote_post_id'))

    op.drop_table('poll_vote')

    with op.batch_alter_table('poll_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_option_post_id'))

    op.drop_table('poll_option')
